# Generated by Django 4.1.2 on 2022-10-14 09:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menutext',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
