# Generated by Django 4.1.2 on 2022-10-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
