# Generated by Django 4.1.2 on 2022-10-14 10:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='shortText',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
